import React,{useState,useMemo} from 'react';
import{createRoot}from'react-dom/client';
import products from './data/products.json';
import{buildBank,prepareSession,audit,API}from'./engine.js';
import './style.css';
const bank=buildBank(products),issues=audit(products),byId=Object.fromEntries(products.map(p=>[p.id,p]));
const counts=Object.fromEntries(products.map(p=>[p.id,bank.filter(q=>q.productId===p.id).length]));
const categories=[...new Set(products.map(p=>p.category?.titleRu?.trim()))];
const image=p=>p.image?'https://api.uzautotrailer.uz'+p.image:null;
const read=()=>{try{return JSON.parse(localStorage.getItem('uat-academy-v1'))||{};}catch{return {};}};
function App(){
 const[page,setPage]=useState('catalog'),[search,setSearch]=useState(''),[category,setCategory]=useState('all'),[mode,setMode]=useState('all'),[stats,setStats]=useState(read),[session,setSession]=useState(null),[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[results,setResults]=useState([]),[finished,setFinished]=useState(false),[learn,setLearn]=useState(null),[size,setSize]=useState('20');
 const wrong=Object.keys(stats).filter(id=>stats[id].last===false),answered=Object.keys(stats).length,mastered=Object.values(stats).filter(s=>s.last===true).length;
 const filtered=products.filter(p=>(category==='all'||p.category?.titleRu?.trim()===category)&&`${p.titleRu} ${p.titleUz}`.toLowerCase().includes(search.toLowerCase()));
 function start(id=null,onlyWrong=false){let qs=bank.filter(q=>(!id||q.productId===id)&&(category==='all'||byId[q.productId].category?.titleRu?.trim()===category)&&(mode==='all'||q.kind===mode)&&(!onlyWrong||wrong.includes(q.id)));if(!qs.length){alert('Ushbu tanlov uchun savol yo‘q. Filtrni o‘zgartiring.');return;}qs=prepareSession(qs);if(size!=='all')qs=qs.slice(0,Number(size));setSession(qs);setIndex(0);setSelected(null);setResults([]);setFinished(false);setLearn(null);setPage('quiz');window.scrollTo(0,0);}
 function choose(v){if(selected!==null)return;const q=session[index],correct=v===q.answer;setSelected(v);setResults(r=>[...r,{id:q.id,correct}]);const next={...stats,[q.id]:{last:correct,attempts:(stats[q.id]?.attempts||0)+1}};setStats(next);try{localStorage.setItem('uat-academy-v1',JSON.stringify(next));}catch{}}
 function next(){if(index+1===session.length)setFinished(true);else{setIndex(index+1);setSelected(null);}window.scrollTo(0,0);}
 function leave(){setSession(null);setPage('catalog');}
 const q=session?.[index],p=q&&byId[q.productId];
 return <div className="shell"><aside><a className="brand" onClick={leave}><span className="brandmark">UAT<span>↗</span></span><span>ACADEMY<small>Mahsulot bilimlari</small></span></a><div className="workspace">O‘QUV MAYDONI</div><nav>{[['catalog','▦','Texnikalar'],['practice','◎','Aralash test'],['mistakes','↺','Xatolar ustida ishlash'],['quality','≋','Manba va tahlil']].map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setSession(null);setLearn(null);}}><b>{icon}</b>{label}{id==='mistakes'&&<em>{wrong.length}</em>}</button>)}</nav><div className="aside-bottom"><span className="live">● API snapshot</span><p>UzAuto TRAILER katalogi</p><small>09.10.2026 · O‘zbekcha interfeys<br/>Texnik manba: ruscha jadval</small></div></aside><main><header><span>UzAuto TRAILER / <strong>{page==='quiz'?'Test jarayoni':'Bilim markazi'}</strong></span><div className="avatar">SH</div></header>
 {page!=='quiz'&&<><div className="intro"><div><div className="eyebrow">UAT ACADEMY / TEXNIK TAYYORGARLIK</div><h1>Texnikani puxta o‘rganing<span>.</span></h1><p>Har bir detalni bilish — mijozga ishonchli javob berishning boshlanishi.</p></div><button className="primary" onClick={()=>start()}>Aralash testni boshlash ↗</button></div><div className="metrics"><div><small>KATALOGDAGI TEXNIKALAR</small><strong>{products.length}<span> model</span></strong></div><div><small>SAVOLLAR BANKI</small><strong>{bank.length.toLocaleString()}<span> savol</span></strong></div><div><small>O‘ZLASHTIRILGAN</small><strong>{mastered}<span> / {bank.length}</span></strong><div className="track"><i style={{width:`${mastered/bank.length*100}%`}}/></div></div><div><small>QAYTA ISHLASH KERAK</small><strong className="orange">{wrong.length}<span> savol</span></strong></div></div></>}
 {page==='catalog'&&!learn&&<><div className="sectionhead"><div><h2>Texnikalar katalogi</h2><p>Modelni tanlang. Xususiyatlarini o‘rganing. Bilimingizni tekshiring.</p></div><span>{filtered.length} ta texnika</span></div><div className="filters"><label className="search">⌕ <input aria-label="Texnika qidirish" placeholder="Model yoki texnika nomini qidirish…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Toifa" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Barcha toifalar</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Savollar soni" value={size} onChange={e=>setSize(e.target.value)}><option value="20">20 savol / test</option><option value="10">10 savol / test</option><option value="all">Barcha savollar</option></select></div><div className="grid">{filtered.map(p=>{let completed=bank.filter(q=>q.productId===p.id&&stats[q.id]?.last===true).length;return <article className="card" key={p.id}><div className="photo"><span className="tag">{p.category?.titleRu}</span>{image(p)&&<img loading="lazy" src={image(p)} alt={p.titleRu} onError={e=>e.currentTarget.style.display='none'}/>}<span className="modelnumber">{String(p.order).padStart(2,'0')}</span></div><div className="cardbody"><small>{p.brand?.name||'UzAuto TRAILER'}</small><h3>{p.titleRu}</h3><div className="cardmeta"><span>{counts[p.id]} savol</span><span>{p.techSpecs.length} ko‘rsatkich</span></div>{!p.techSpecs.length&&<p className="warning">Texnik jadval mavjud emas</p>}<div className="track"><i style={{width:`${completed/counts[p.id]*100}%`}}/></div><div className="cardactions"><button onClick={()=>setLearn(p)}>O‘rganish</button><button onClick={()=>start(p.id)}>Testni boshlash ↗</button></div></div></article>})}</div>{!filtered.length&&<div className="empty">Bu qidiruvga mos texnika topilmadi.</div>}</>}
 {learn&&page==='catalog'&&<section className="panel"><button className="textbutton" onClick={()=>setLearn(null)}>← Katalogga qaytish</button><h2>{learn.titleRu}</h2><p className="muted">Quyida API’dagi RU ma’lumotlari aynan keltirilgan.</p><button className="primary" onClick={()=>start(learn.id)}>Shu model bo‘yicha test ↗</button><p className="description">{learn.contentRu}</p>{!learn.techSpecs.length&&<p className="warning">Bu model uchun API texnik jadval qaytarmagan. Tafsilotlar taxmin bilan to‘ldirilmagan.</p>}<div className="tablewrap"><table><thead><tr><th>Bo‘lim</th><th>Ko‘rsatkich</th><th>Qiymat</th></tr></thead><tbody>{learn.techSpecs.map(s=><tr key={s.id}><td>{s.section?.titleRu}</td><td>{s.keyRu}</td><td>{s.valRu}</td></tr>)}</tbody></table></div></section>}
 {(page==='practice'||page==='mistakes')&&<section className="panel setup"><span className="eyebrow">{page==='mistakes'?'QAYTA MUSTAHKAMLASH':'O‘ZINGIZNI SINAB KO‘RING'}</span><h2>{page==='mistakes'?'Xatolardan bilimga.':'Bir test. Turli texnikalar.'}</h2><p>Variant tanlanishi bilan natija, to‘g‘ri javob va API’dagi dalil ko‘rinadi. Har bir testda savollar va A–D tartibi qayta aralashtiriladi.</p><div className="filters"><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Test toifasi"><option value="all">Barcha toifalar</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value)} aria-label="Savol turi"><option value="all">Barcha savol turlari</option><option value="detail">Batafsil ko‘rsatkichlar</option><option value="configuration">Murakkab juftliklar</option></select><select value={size} onChange={e=>setSize(e.target.value)} aria-label="Test uzunligi"><option value="10">10 savol</option><option value="20">20 savol</option><option value="all">Barcha savollar</option></select></div><button className="primary" disabled={page==='mistakes'&&!wrong.length} onClick={()=>start(null,page==='mistakes')}>{page==='mistakes'?`${wrong.length} ta xatoni qayta ishlash`:'Testni boshlash'} →</button><p className="muted">Natijalar shu brauzerda saqlanadi. To‘g‘ri qayta javob berilgan savol xatolar ro‘yxatidan chiqadi.</p></section>}
 {page==='quality'&&<section className="panel"><h2>Manba shaffofligi</h2><p>To‘liq javob massivida {products.length} model, {products.reduce((a,p)=>a+p.techSpecs.length,0)} texnik qator bor. Har bir model test bilan qamrab olingan. Bo‘sh jadvalli modellar faqat katalog savollariga ega.</p><a href={API} target="_blank" rel="noreferrer">API manbasini ochish ↗</a><p>To‘g‘ri javoblar RU texnik jadvalidan olinadi. Bir xil nomli maydonlarda bo‘lim savolda ko‘rsatiladi. Chalg‘ituvchi variantlar shu maydonning boshqa modellardagi qiymatlari yoki yaqin sonli variantlardan tuziladi; ular ushbu texnika haqida tasdiqlangan fakt hisoblanmaydi. Narx testga kiritilmagan. UZ/EN tarjimalari javob kaliti sifatida ishlatilmagan.</p><h3>Tekshirish talab qiladigan joylar · {issues.length}</h3>{issues.map((x,i)=><div className="issue" key={i}><strong>{x.title}</strong><p>{x.message}</p></div>)}<p className="muted">Bu avtomatik va maqsadli tekshiruvlar ro‘yxati. API’dagi barcha mazmuniy xatolar yo‘qligiga kafolat bermaydi.</p></section>}
 {page==='quiz'&&session&&!finished&&<div className="quiz"><div className="quiztop"><button className="textbutton" onClick={leave}>← Testdan chiqish</button><span>{index+1} / {session.length} savol</span><span>{results.filter(x=>x.correct).length} to‘g‘ri</span></div><div className="track quiztrack"><i style={{width:`${(index+(selected!==null?1:0))/session.length*100}%`}}/></div><div className="quizmodel">{image(p)&&<img src={image(p)} alt="" onError={e=>e.currentTarget.style.display='none'}/>}<div><small>{p.category?.titleRu}</small><h2>{p.titleRu}</h2></div></div><section className="question"><div className="eyebrow">{q.kind==='configuration'?'MURAKKAB JUFTLIK':'BATAFSIL BILIM'} / {q.section}</div><h1>{q.prompt}</h1><p className="muted">Bitta to‘g‘ri javobni tanlang. Manba: API ruscha jadvali.</p><div className="options">{q.options.map((v,i)=><button key={v} disabled={selected!==null} onClick={()=>choose(v)} className={selected===null?'':v===q.answer?'correct':v===selected?'incorrect':'dim'}><span>{'ABCD'[i]}</span><b>{v}</b><em>{selected!==null&&(v===q.answer?'✓':v===selected?'×':'')}</em></button>)}</div>{selected!==null&&<div className={'feedback '+(selected===q.answer?'good':'bad')} role="status"><h3>{selected===q.answer?'To‘g‘ri javob!':'Bu safar xato. Keling, mustahkamlaymiz.'}</h3><p>{q.explanation}</p>{q.evidence.map((e,i)=><div key={i} className="evidence"><small>{e.section} / {e.key}</small><strong>{e.value}</strong></div>)}<details><summary>API dalilini ko‘rish</summary><p>{q.source}</p><a href={API} target="_blank" rel="noreferrer">API manbasi ↗</a></details></div>}<div className="questionfoot"><span>Javob berilgach, variantlarni almashtirib bo‘lmaydi.</span><button className="primary" disabled={selected===null} onClick={next}>{index+1===session.length?'Natijani ko‘rish':'Keyingi savol'} →</button></div></section></div>}
 {page==='quiz'&&finished&&<section className="panel result"><div className="eyebrow">TEST YAKUNLANDI</div><h1>{Math.round(results.filter(x=>x.correct).length/results.length*100)}<span>%</span></h1><h2>{results.filter(x=>x.correct).length} / {results.length} ta to‘g‘ri javob</h2><p>Bilim — takror bilan mustahkamlanadi. Xato javoblar qayta ishlash uchun saqlandi.</p><button className="primary" onClick={()=>{const missed=session.filter(q=>results.some(r=>r.id===q.id&&!r.correct));if(missed.length){setSession(prepareSession(missed));setIndex(0);setSelected(null);setResults([]);setFinished(false);}else leave();}}>{results.some(r=>!r.correct)?'Shu testdagi xatolarni takrorlash':'Katalogga qaytish'} →</button><button className="textbutton" onClick={leave}>Katalogga qaytish</button><div className="review">{results.map((r,i)=><div key={r.id}><span>{r.correct?'✓':'×'}</span><div><strong>{byId[session[i].productId].titleRu}</strong><p>{session[i].evidence.map(e=>`${e.key}: ${e.value}`).join(' · ')}</p></div></div>)}</div></section>}
 <footer>UAT ACADEMY <span>Bilimdan ishonchga.</span><small>API holati: 9 oktabr 2026 · {answered} savol ishlangan</small></footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
